name: marakzia_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  path: ^1.9.0
  sqflite: ^2.4.1
  dio: ^5.7.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  dropdown_search: ^6.0.2
  fluttertoast: ^8.2.12
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: any
  package_info_plus: ^8.3.0


flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
flutter_intl:
  enabled: true
